export { Aluno } from './models/aluno.model';
export { Cidade } from './models/cidade';
export { Curso } from './models/curso.model';
export { Document} from './models/document.model';
export { Endereco } from './models/endereco.model';
export { EstadoBr } from './models/estado-br.model';
export { Faculdade } from './models/faculdade.model';
export { Funcionario } from './models/funcionario.model';
export { MENSAGENS } from './models/mensagens.model';
export { Professor } from './models/professor.model';
export { ProfessorBrief } from './models/professorBrief.model';
export { User } from './models/user.model';
export { CreateOrUpdate } from './abstract/create-update.component';
export { PageList } from './abstract/list.component';
